# language_scripts.py
"""
Mapping of ISO 15924 script codes to their formal script names.
Source: https://en.wikipedia.org/wiki/ISO_15924 and Unicode Consortium
"""

SCRIPT_NAMES = {
    "Adlm": "Adlam",
    "Afak": "Afaka",
    "Aghb": "Caucasian Albanian",
    "Ahom": "Ahom, Tai Ahom",
    "Arab": "Arabic",
    "Aran": "Arabic (Nastaliq variant)",
    "Armi": "Imperial Aramaic",
    "Armn": "Armenian",
    "Avst": "Avestan",
    "Bali": "Balinese",
    "Bamu": "Bamum",
    "Bass": "Bassa Vah",
    "Batk": "Batak",
    "Beng": "Bengali (Bangla)",
    "Bhks": "Bhaiksuki",
    "Bopo": "Bopomofo",
    "Brah": "Brahmi",
    "Brai": "Braille",
    "Bugi": "Buginese",
    "Buhd": "Buhid",
    "Cakm": "Chakma",
    "Cans": "Unified Canadian Aboriginal Syllabics",
    "Cari": "Carian",
    "Cham": "Cham",
    "Cher": "Cherokee",
    "Copt": "Coptic",
    "Cprt": "Cypriot syllabary",
    "Cyrl": "Cyrillic",
    "Deva": "Devanagari (Nagari)",
    "Dsrt": "Deseret (Mormon)",
    "Dupl": "Duployan shorthand, Duployan stenography",
    "Egyp": "Egyptian hieroglyphs",
    "Elba": "Elbasan",
    "Ethi": "Ethiopic (Geʻez)",
    "Geor": "Georgian (Mkhedruli and Mtavruli)",
    "Glag": "Glagolitic",
    "Goth": "Gothic",
    "Gran": "Grantha",
    "Grek": "Greek",
    "Gujr": "Gujarati",
    "Guru": "Gurmukhi",
    "Hang": "Hangul",
    "Hani": "Han (Hanzi, Kanji, Hanja)",
    "Hano": "Hanunoo (Hanunóo)",
    "Hans": "Han (Simplified variant)",
    "Hant": "Han (Traditional variant)",
    "Hebr": "Hebrew",
    "Hira": "Hiragana",
    "Hrkt": "Japanese syllabaries (Hiragana + Katakana)",
    "Jamo": "Jamo subset of Hangul",
    "Java": "Javanese",
    "Jpan": "Japanese (Han + Hiragana + Katakana)",
    "Kali": "Kayah Li",
    "Kana": "Katakana",
    "Khar": "Kharoshthi",
    "Khmr": "Khmer",
    "Knda": "Kannada",
    "Kore": "Korean (Hangul + Han)",
    "Lana": "Tai Tham (Lanna)",
    "Laoo": "Lao",
    "Latf": "Latin (Fraktur variant)",
    "Latg": "Latin (Gaelic variant)",
    "Latn": "Latin",
    "Lepc": "Lepcha (Róng)",
    "Limb": "Limbu",
    "Lina": "Linear A",
    "Linb": "Linear B",
    "Lisu": "Lisu (Fraser)",
    "Lyci": "Lycian",
    "Lydi": "Lydian",
    "Mahj": "Mahajani",
    "Maka": "Makasar",
    "Mand": "Mandaic, Mandaean",
    "Mani": "Manichaean",
    "Marc": "Marchen",
    "Mend": "Mende Kikakui",
    "Merc": "Meroitic Cursive",
    "Mero": "Meroitic Hieroglyphs",
    "Mlym": "Malayalam",
    "Modi": "Modi, Moḍī",
    "Mong": "Mongolian",
    "Mroo": "Mro, Mru",
    "Mtei": "Meitei Mayek (Meithei, Meetei)",
    "Mult": "Multani",
    "Mymr": "Myanmar (Burmese)",
    "Nand": "Nandinagari",
    "Narb": "Old North Arabian (Ancient North Arabian)",
    "Nbat": "Nabataean",
    "Newa": "Newa, Newar, Newari, Nepāla lipi",
    "Nkoo": "N’Ko",
    "Ogam": "Ogham",
    "Olck": "Ol Chiki (Ol Cemet’, Ol, Santali)",
    "Orkh": "Old Turkic, Orkhon Runic",
    "Orya": "Oriya (Odia)",
    "Osge": "Osage",
    "Osma": "Osmanya",
    "Phag": "Phags-pa",
    "Phli": "Inscriptional Pahlavi",
    "Phlp": "Psalter Pahlavi",
    "Phnx": "Phoenician",
    "Plrd": "Miao (Pollard)",
    "Prti": "Inscriptional Parthian",
    "Rjng": "Rejang (Redjang, Kaganga)",
    "Runr": "Runic",
    "Samr": "Samaritan",
    "Sarb": "Old South Arabian",
    "Saur": "Saurashtra",
    "Sgnw": "SignWriting",
    "Shaw": "Shavian (Shaw)",
    "Shrd": "Sharada, Śāradā",
    "Sidd": "Siddham, Siddhaṃ, Siddhamātṛkā",
    "Sind": "Khudawadi, Sindhi",
    "Sinh": "Sinhala",
    "Sora": "Sora Sompeng",
    "Sund": "Sundanese",
    "Sylo": "Syloti Nagri",
    "Syrc": "Syriac",
    "Tagb": "Tagbanwa",
    "Takr": "Takri, Ṭākrī, Ṭāṅkrī",
    "Tale": "Tai Le",
    "Talu": "New Tai Lue",
    "Taml": "Tamil",
    "Tang": "Tangut",
    "Tavt": "Tai Viet",
    "Telu": "Telugu",
    "Tfng": "Tifinagh (Berber)",
    "Tglg": "Tagalog (Baybayin, Alibata)",
    "Thaa": "Thaana",
    "Thai": "Thai",
    "Tibt": "Tibetan",
    "Tirh": "Tirhuta",
    "Ugar": "Ugaritic",
    "Vaii": "Vai",
    "Wara": "Warang Citi (Varang Kshiti)",
    "Xpeo": "Old Persian",
    "Xsux": "Cuneiform, Sumero-Akkadian",
    "Yiii": "Yi",
    "Zinh": "Inherited",
    "Zmth": "Mathematical notation",
    "Zsye": "Symbols (emoji variant)",
    "Zsym": "Symbols",
    "Zxxx": "Unwritten documents",
    "Zyyy": "Common",
    "Zzzz": "Unknown or Uncoded",
}


def get_script_formal_name(script_code: str) -> str:
    """Return the formal script name for a given ISO 15924 script code."""
    return SCRIPT_NAMES.get(script_code, script_code)
